name: Build docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    
    - name: Install yarn
      run: yarn install -g 
     
    - name: yarn build+install
      run: |
          yarn install --frozen-lockfile
          yarn tsc
          yarn build:all
      
    - name: Log in to container registry
      uses: docker/login-action@v1
      with:
        registry: rabackstagereg.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: rabackstagereg.azurecr.io/backstage:${{ github.sha }}
        file: --file packages/backend/Dockerfile 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          azcliversion: 2.20.0
          inlineScript: |
            echo "Installing containerapp extension"
            az provider register --namespace Microsoft.Web
            az extension add --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/containerapp-0.1.12-py2.py3-none-any.whl --yes
            echo "Starting Deploying"
            az containerapp update -n backstage -g demo -i rabackstagereg.azurecr.io/backstage:${{ github.sha }} --registry-login-server rabackstagereg.azurecr.io --registry-username  ${{ secrets.REGISTRY_USERNAME }} --registry-password ${{ secrets.REGISTRY_PASSWORD }} --debug

#     - name: 'Build and push image'
#       uses: azure/docker-login@v1
#       with:
#         login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}.azurecr.io
#         username: ${{ secrets.REGISTRY_USERNAME }}
#         password: ${{ secrets.REGISTRY_PASSWORD }}  
    
#     - run: |
#         docker image build . --file packages/backend/Dockerfile --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/backstage:${{ github.sha }}
#         docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/backstage:${{ github.sha }}
 
#     - name: 'Az CLI login'
#       uses: azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}
#         allow-no-subscriptions: true

#     - uses: azure/webapps-deploy@v2
#       with:
#         app-name: '${{ secrets.APP_NAME }}'
#         images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/backstage:${{ github.sha }}
